ALTER TABLE "Offer" ADD COLUMN "teamId" INTEGER;
ALTER TABLE "Offer" ADD CONSTRAINT "Offer_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Request" ADD COLUMN "teamId" INTEGER;
ALTER TABLE "Request" ADD CONSTRAINT "Request_teamId_fkey" FOREIGN KEY ("teamId") REFERENCES "Team"("id") ON DELETE SET NULL ON UPDATE CASCADE;
